/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as ChangelogRouteRouteImport } from './routes/changelog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as DocsSideloadRouteImport } from './routes/docs/sideload'
import { Route as DocsSecurityRouteImport } from './routes/docs/security'
import { Route as DocsPermissionsRouteImport } from './routes/docs/permissions'
import { Route as DocsFaqRouteImport } from './routes/docs/faq'
import { Route as DocsComparisonRouteImport } from './routes/docs/comparison'
import { Route as DocsCommandsRouteImport } from './routes/docs/commands'
import { Route as DocsArchitectureRouteImport } from './routes/docs/architecture'
import { Route as ChangelogExtensionRouteImport } from './routes/changelog/extension'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRouteRoute = ChangelogRouteRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChangelogRouteRoute,
} as any)
const DocsSideloadRoute = DocsSideloadRouteImport.update({
  id: '/sideload',
  path: '/sideload',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSecurityRoute = DocsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPermissionsRoute = DocsPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComparisonRoute = DocsComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsCommandsRoute = DocsCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRouteRoute,
} as any)
const ChangelogExtensionRoute = ChangelogExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => ChangelogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/changelog/extension': typeof ChangelogExtensionRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/comparison': typeof DocsComparisonRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/permissions': typeof DocsPermissionsRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/sideload': typeof DocsSideloadRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/changelog/extension': typeof ChangelogExtensionRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/comparison': typeof DocsComparisonRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/permissions': typeof DocsPermissionsRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/sideload': typeof DocsSideloadRoute
  '/changelog': typeof ChangelogIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/changelog/extension': typeof ChangelogExtensionRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/comparison': typeof DocsComparisonRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/permissions': typeof DocsPermissionsRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/sideload': typeof DocsSideloadRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/docs'
    | '/privacy'
    | '/changelog/extension'
    | '/docs/architecture'
    | '/docs/commands'
    | '/docs/comparison'
    | '/docs/faq'
    | '/docs/permissions'
    | '/docs/security'
    | '/docs/sideload'
    | '/changelog/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/changelog/extension'
    | '/docs/architecture'
    | '/docs/commands'
    | '/docs/comparison'
    | '/docs/faq'
    | '/docs/permissions'
    | '/docs/security'
    | '/docs/sideload'
    | '/changelog'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/docs'
    | '/privacy'
    | '/changelog/extension'
    | '/docs/architecture'
    | '/docs/commands'
    | '/docs/comparison'
    | '/docs/faq'
    | '/docs/permissions'
    | '/docs/security'
    | '/docs/sideload'
    | '/changelog/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRouteRoute: typeof ChangelogRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof ChangelogRouteRoute
    }
    '/docs/sideload': {
      id: '/docs/sideload'
      path: '/sideload'
      fullPath: '/docs/sideload'
      preLoaderRoute: typeof DocsSideloadRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/security': {
      id: '/docs/security'
      path: '/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsSecurityRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/permissions': {
      id: '/docs/permissions'
      path: '/permissions'
      fullPath: '/docs/permissions'
      preLoaderRoute: typeof DocsPermissionsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/comparison': {
      id: '/docs/comparison'
      path: '/comparison'
      fullPath: '/docs/comparison'
      preLoaderRoute: typeof DocsComparisonRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/commands': {
      id: '/docs/commands'
      path: '/commands'
      fullPath: '/docs/commands'
      preLoaderRoute: typeof DocsCommandsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/changelog/extension': {
      id: '/changelog/extension'
      path: '/extension'
      fullPath: '/changelog/extension'
      preLoaderRoute: typeof ChangelogExtensionRouteImport
      parentRoute: typeof ChangelogRouteRoute
    }
  }
}

interface ChangelogRouteRouteChildren {
  ChangelogExtensionRoute: typeof ChangelogExtensionRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
}

const ChangelogRouteRouteChildren: ChangelogRouteRouteChildren = {
  ChangelogExtensionRoute: ChangelogExtensionRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
}

const ChangelogRouteRouteWithChildren = ChangelogRouteRoute._addFileChildren(
  ChangelogRouteRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsCommandsRoute: typeof DocsCommandsRoute
  DocsComparisonRoute: typeof DocsComparisonRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsPermissionsRoute: typeof DocsPermissionsRoute
  DocsSecurityRoute: typeof DocsSecurityRoute
  DocsSideloadRoute: typeof DocsSideloadRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsCommandsRoute: DocsCommandsRoute,
  DocsComparisonRoute: DocsComparisonRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsPermissionsRoute: DocsPermissionsRoute,
  DocsSecurityRoute: DocsSecurityRoute,
  DocsSideloadRoute: DocsSideloadRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRouteRoute: ChangelogRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
